# one of the compressors defined in `external_compressors`
# or the internal lz5 compressor "lznint"
default_compressor = "lznint"

[external_compressors.AmoebaCompress]
path = "AmoebaCompress"
params = ["-c", "-f", "{{input}}", "-o", "{{output}}"]
compressed_extension = "lz5"
